/**
 * Stable, machine-readable error codes returned in the `code` field of the
 * error envelope (requirements/TDD.md §11.2). Clients branch on these, so
 * treat them as part of the API contract: add freely, never rename.
 */
export const ErrorCode = {
  // 4xx — client
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  RATE_LIMITED: 'RATE_LIMITED',

  // 409 — optimistic concurrency and state
  STALE_VERSION: 'STALE_VERSION',
  ILLEGAL_STATE_TRANSITION: 'ILLEGAL_STATE_TRANSITION',
  APPROVAL_ALREADY_DECIDED: 'APPROVAL_ALREADY_DECIDED',

  // 4xx — business rules
  SEGREGATION_OF_DUTIES: 'SEGREGATION_OF_DUTIES',
  POLICY_BLOCKED: 'POLICY_BLOCKED',
  POLICY_EXCEPTION_UNJUSTIFIED: 'POLICY_EXCEPTION_UNJUSTIFIED',
  DUPLICATE_UNRESOLVED: 'DUPLICATE_UNRESOLVED',
  CLAIM_NOT_SUBMITTABLE: 'CLAIM_NOT_SUBMITTABLE',
  EXPENSE_NOT_CLAIMABLE: 'EXPENSE_NOT_CLAIMABLE',
  RECEIPT_REQUIRED: 'RECEIPT_REQUIRED',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',

  // 5xx — server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
