/**
 * Emits the two web-facing artifacts from the single TS token source:
 *
 *   dist/tokens.css    :root custom properties (--cd-*)
 *   dist/tailwind.css  Tailwind v4 @theme block (--color-*, --spacing-*, ...)
 *
 * Both are committed and covered by `pnpm codegen:check`, so a token edit that
 * skips the rebuild fails CI instead of silently drifting.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { color, gradient } from '../src/color.js';
import { duration, easing } from '../src/motion.js';
import { layout } from '../src/layout.js';
import { radius } from '../src/radius.js';
import { shadow } from '../src/shadow.js';
import { space } from '../src/space.js';
import { fontFamily, fontSize, fontWeight, letterSpacing } from '../src/typography.js';

const outDir = resolve(dirname(fileURLToPath(import.meta.url)), '../dist');

const kebab = (s: string) =>
  s
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([a-zA-Z])(\d)/g, '$1-$2')
    .toLowerCase();

const gradientCss = `linear-gradient(${gradient.accent.angleDeg}deg, ${gradient.accent.stops
  .map((s) => `${s.color} ${Number((s.position * 100).toFixed(4))}%`)
  .join(', ')})`;

const lines: string[] = [];
const push = (comment: string, entries: [string, string | number][]) => {
  lines.push(`  /* ${comment} */`);
  for (const [k, v] of entries) lines.push(`  ${k}: ${v};`);
  lines.push('');
};

push(
  'colour',
  Object.entries(color).map(([k, v]) => [`--cd-${kebab(k)}`, v] as [string, string]),
);
lines.push(`  --cd-accent-grad: ${gradientCss};`, '');
push(
  'space (4pt)',
  Object.entries(space).map(([k, v]) => [`--cd-sp-${k}`, `${v}px`] as [string, string]),
);
push(
  'radius',
  Object.entries(radius).map(([k, v]) => [`--cd-r-${kebab(k)}`, `${v}px`] as [string, string]),
);
push(
  'type',
  [
    ...Object.entries(fontSize).map(([k, v]) => [`--cd-fs-${kebab(k)}`, `${v}px`]),
    ...Object.entries(fontWeight).map(([k, v]) => [`--cd-fw-${kebab(k)}`, v]),
    ...Object.entries(letterSpacing).map(([k, v]) => [`--cd-track-${kebab(k)}`, v]),
    ['--cd-font-ui', fontFamily.ui],
  ] as [string, string][],
);
push(
  'elevation + motion',
  [
    ...Object.entries(shadow).map(([k, v]) => [`--cd-shadow-${k}`, v]),
    ['--cd-ease', easing.standard],
    ...Object.entries(duration).map(([k, v]) => [`--cd-t-${k}`, `${v}ms`]),
  ] as [string, string][],
);
push(
  'layout',
  Object.entries(layout).map(([k, v]) => [`--cd-${kebab(k)}`, `${v}px`] as [string, string]),
);

const header = `/* GENERATED by packages/tokens/scripts/build-css.ts — do not edit.
   Source of truth: packages/tokens/src/*.ts
   Palette: "Clear Ledger" v2.0 (reference/ClaimDesk_Mobile_v2.html) */\n`;

mkdirSync(outDir, { recursive: true });
writeFileSync(`${outDir}/tokens.css`, `${header}\n:root {\n${lines.join('\n')}}\n`, 'utf8');

// Tailwind v4: theme comes from an @theme block, not a JS config file.
const tw: string[] = [];
for (const [k, v] of Object.entries(color)) tw.push(`  --color-${kebab(k)}: ${v};`);
tw.push('');
for (const [k, v] of Object.entries(space)) tw.push(`  --spacing-${k}: ${v}px;`);
tw.push('');
for (const [k, v] of Object.entries(radius)) tw.push(`  --radius-${kebab(k)}: ${v}px;`);
tw.push('');
for (const [k, v] of Object.entries(fontSize)) tw.push(`  --text-${kebab(k)}: ${v}px;`);
tw.push('');
for (const [k, v] of Object.entries(shadow)) tw.push(`  --shadow-${k}: ${v};`);
tw.push('', `  --font-ui: ${fontFamily.ui};`, `  --ease-standard: ${easing.standard};`);

writeFileSync(`${outDir}/tailwind.css`, `${header}\n@theme {\n${tw.join('\n')}\n}\n`, 'utf8');

console.log(`tokens: wrote dist/tokens.css and dist/tailwind.css`);
